apiVersion: v2
name: urumi-woocommerce
description: Production-ready WooCommerce wrapper chart for Stores
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - wordpress
  - woocommerce
  - ecommerce
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/wordpress
dependencies:
  - name: wordpress
    version: "24.1.2"
    repository: "oci://registry-1.docker.io/bitnamicharts"
